//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPServer.UI.PowerShell.ManagementServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.andrekirst.de/SIPServer/IManagementService", ConfigurationName="ManagementServiceReference.IManagementServiceContract", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IManagementServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.andrekirst.de/SIPServer/IManagementService/IManagementServiceContract/" +
            "Login", ReplyAction="http://www.andrekirst.de/SIPServer/IManagementService/IManagementServiceContract/" +
            "LoginResponse")]
        void Login();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://www.andrekirst.de/SIPServer/IManagementService/IManagementServiceContract/" +
            "Logout", ReplyAction="http://www.andrekirst.de/SIPServer/IManagementService/IManagementServiceContract/" +
            "LogoutResponse")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.andrekirst.de/SIPServer/IManagementService/IManagementServiceContract/" +
            "GetSIPServerList", ReplyAction="http://www.andrekirst.de/SIPServer/IManagementService/IManagementServiceContract/" +
            "GetSIPServerListResponse")]
        System.Collections.Generic.List<SIPServer.Model.Database.SIPServer> GetSIPServerList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IManagementServiceContractChannel : SIPServer.UI.PowerShell.ManagementServiceReference.IManagementServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ManagementServiceContractClient : System.ServiceModel.ClientBase<SIPServer.UI.PowerShell.ManagementServiceReference.IManagementServiceContract>, SIPServer.UI.PowerShell.ManagementServiceReference.IManagementServiceContract {
        
        public ManagementServiceContractClient() {
        }
        
        public ManagementServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagementServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Login() {
            base.Channel.Login();
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Collections.Generic.List<SIPServer.Model.Database.SIPServer> GetSIPServerList() {
            return base.Channel.GetSIPServerList();
        }
    }
}
